name: Set up environment
description: Set up a conda environment for running project tests and checks

inputs:
  python-version:
    description: The version of Python to install, as a string
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    - name: Cache conda env
      id: cache-conda
      uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
      env:
        cache-name: conda-env-cache
      with:
        cache: 'pip'
        path: '/usr/share/miniconda/envs'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Create Environment
      shell: bash
      if: ${{ steps.cache-conda.outputs.cache-hit == false }}
      # NOTE: We use `sed` to force a Python version in the `environment.yaml` file
      run: |
        conda update -n base -c defaults conda
        source $CONDA/etc/profile.d/conda.sh
        conda init bash
        sed -i 's/- python >=3.*$/- python ${{ inputs.python-version }}.*/' environment.yaml
        conda env create -f environment.yaml --name ${{ inputs.project-name }} --force
        conda run --name ${{ inputs.project-name }} pip install .
