on:
  push:
    branches:
      - main
  pull_request:

name: Test

env:
  PROJECT_NAME: TODO

jobs:
  # NOTE: Tests run via `pre-commit` on 3.11; All other versions of Python run just the tests.
  pre-commit:
      name: Run pre-commit on 3.11
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        - uses: ./.github/actions/setup-env
          with:
            python-version: "3.11"
            project-name: ${{ env.PROJECT_NAME }}
        # Executes `pre-commit` with the `make` directive to ensure all dependencies are found
        - run: |
            source $CONDA/bin/activate
            conda activate ${{ env.PROJECT_NAME }}
            make pre-commit
  test:
      runs-on: ubuntu-latest
      name: Test on ${{ matrix.python-version }}
      strategy:
        matrix:
          python-version: ["3.11"] # TODO: Bump this to 3.12 when supported and drop 3.11 (covered in pre-commit)
      steps:
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        - uses: ./.github/actions/setup-env
          with:
            python-version: ${{ matrix.python-version }}
        - run: |
            source $CONDA/bin/activate
            conda activate ${{ env.PROJECT_NAME }}
            make test
  build-recipe:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
          with:
            repository: AnacondaRecipes/${{ env.PROJECT_NAME }}-feedstock
            path: ./feedstock
        - name: Cache conda env
          id: cache-conda
          uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
          env:
            cache-name: conda-env-cache
          with:
            path: '/usr/share/miniconda/envs'
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/environment.yml') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-
        - name: Build package
          run: |
            cp -r ./feedstock/abs.yaml ./feedstock/recipe .
            source $CONDA/bin/activate
            conda install conda-build
            conda-build -c distro-tooling .
